CREATE TABLE IF NOT EXISTS player_vehicle_crimes
(
  id INT AUTO_INCREMENT NOT NULL,
  license_plate VARCHAR(24) NOT NULL,
  crime VARCHAR(128) NOT NULL,
  reporter VARCHAR(24) NOT NULL,
  date DATETIME NOT NULL,
  fine INT UNSIGNED NOT NULL,
  PRIMARY KEY(id)
)ENGINE=INNODB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
