
CREATE TABLE players
(
  id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  username VARCHAR(24) DEFAULT 'Kas' NOT NULL,
  password VARCHAR(128) DEFAULT 'klaida' NOT NULL,
  secret_question VARCHAR(128) NOT NULL,
  secret_answer VARCHAR(128) NOT NULL,
  level INT DEFAULT 1 NOT NULL,
  admin_level INT DEFAULT 0 NOT NULL,
  connected_time INT DEFAULT 0 NOT NULL,
  box_style TINYINT UNSIGNED DEFAULT 4 NOT NULL,
  sex VARCHAR(11) DEFAULT 'Vyras' NOT NULL,
  age INT DEFAULT 0 NOT NULL,
  origin VARCHAR(24) DEFAULT 'Nenustatyta' NOT NULL,
  disease INT DEFAULT 0 NOT NULL,
  respect INT DEFAULT 0 NOT NULL,
  money INT DEFAULT 320 NOT NULL,
  bank INT DEFAULT 0 NOT NULL,
  deaths INT DEFAULT 0 NOT NULL,
  wanted_level INT DEFAULT 0 NOT NULL,
  job INT DEFAULT 0 NOT NULL,
  leader INT DEFAULT 0 NOT NULL,
  member INT DEFAULT 0 NOT NULL,
  pJobCar INT DEFAULT 0 NOT NULL,
  rank INT DEFAULT 0 NOT NULL,
  skin INT DEFAULT 212 NOT NULL,
  job_contract TINYINT DEFAULT 0 NOT NULL,
  phonenumber INT DEFAULT 0 NOT NULL,
  House INT DEFAULT 0 NOT NULL,
  CarLic INT DEFAULT 0 NOT NULL,
  FlyLic INT DEFAULT 0 NOT NULL,
  BoatLic INT DEFAULT 0 NOT NULL,
  MotoLic INT DEFAULT 0 NOT NULL,
  GunLic INT DEFAULT 0 NOT NULL,
  payday INT DEFAULT 0 NOT NULL,
  pay_day_had INT DEFAULT 0 NOT NULL,
  warnings INT DEFAULT 0 NOT NULL,
  virtual_world INT DEFAULT 0 NOT NULL,
  locked INT DEFAULT 0 NOT NULL,
  radio_channel INT DEFAULT 0 NOT NULL,
  ucpuser INT DEFAULT 0 NOT NULL,
  inventory VARCHAR(80) DEFAULT '0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/' NOT NULL,
  weapons VARCHAR(56) DEFAULT '0/0/0/0/0/0/0/0/' NOT NULL,
  pDubKey INT DEFAULT 0 NOT NULL,
  JobSkill INT DEFAULT 0 NOT NULL,
  JobLevel INT DEFAULT 0 NOT NULL,
  LeftTime INT DEFAULT 0 NOT NULL,
  DriverWarn INT DEFAULT 0 NOT NULL,
  Tester INT DEFAULT 0 NOT NULL,
  pFines INT DEFAULT 0 NOT NULL,
  pPFines INT DEFAULT 0 NOT NULL,
  pDutyT INT DEFAULT 0 NOT NULL,
  Donator INT DEFAULT 0 NOT NULL,
  Accepted VARCHAR(255) NOT NULL,
  WalkStyle INT NOT NULL,
  TalkStyle INT NOT NULL,
  TelNrKeite INT DEFAULT 0 NOT NULL,
  MasinosNrKeite INT DEFAULT 0 NOT NULL,
  DuziusKeite INT DEFAULT 0 NOT NULL,
  VardaKeite INT DEFAULT 0 NOT NULL,
  SenasVardas VARCHAR(255) DEFAULT 'Nera' NOT NULL,
  HeroineAddict SMALLINT DEFAULT 0 NOT NULL,
  AmfaAddict SMALLINT DEFAULT 0 NOT NULL,
  MetamfaAddict SMALLINT DEFAULT 0 NOT NULL,
  CocaineAddict SMALLINT DEFAULT 0 NOT NULL,
  playerIP VARCHAR(32) DEFAULT '127.0.0.1' NOT NULL,
  playerLastLogOn TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  spawn_type SMALLINT NOT NULL DEFAULT '0',
  spawn_ui INT NOT NULL DEFAULT '0',
  Card VARCHAR(256) DEFAULT 'Tuščia' NOT NULL,
  ForumName VARCHAR(256) DEFAULT 'Neivesta' NOT NULL,
  aDutyTime INT DEFAULT 0 NOT NULL,
  DonatorDate TIMESTAMP DEFAULT '0000-00-00 00:00:00' NOT NULL,
  HaveNameChange INT DEFAULT 0 NOT NULL,
  HavePhNrChange INT DEFAULT 0 NOT NULL,
  HaveVehPlatesChange INT DEFAULT 0 NOT NULL,
  HaveVehDestr INT DEFAULT 0 NOT NULL,
  ExtazyAddict SMALLINT DEFAULT 0 NOT NULL,
  PCPAddict SMALLINT DEFAULT 0 NOT NULL,
  CrackAddict SMALLINT DEFAULT 0 NOT NULL,
  OpiumAddict SMALLINT DEFAULT 0 NOT NULL,
  Points SMALLINT DEFAULT 0 NOT NULL,
  HealthLevel SMALLINT DEFAULT 0 NOT NULL,
  StrengthLevel SMALLINT DEFAULT 0 NOT NULL,
  ISP VARCHAR(128) DEFAULT '' NOT NULL,
  JobHours INT DEFAULT 0 NOT NULL,
  Hunger TINYINT UNSIGNED DEFAULT 0 NOT NULL,
  TotalPaycheck INT UNSIGNED DEFAULT 0 NOT NULL,
  radio_slot TINYINT UNSIGNED DEFAULT 1 NOT NULL
);


CREATE TABLE IF NOT EXISTS player_crashes
(
  player_id INT(11) NOT NULL,
  timestamp DATETIME NOT NULL,
  pos_x FLOAT NOT NULL,
  pos_y FLOAT NOT NULL,
  pos_z FLOAT NOT NULL,
  PRIMARY KEY(player_id)
);
ALTER TABLE player_crashes ADD FOREIGN KEY(player_id) REFERENCES players(id) ON DELETE CASCADE;


CREATE TABLE IF NOT EXISTS player_jailtime
(
  id INT AUTO_INCREMENT NOT NULL,
  player_id INT NOT NULL,
  remaining_time INT NOT NULL,
  type VARCHAR(16) NOT NULL,
  jailer_name VARCHAR(24) NOT NUlL,
  jail_date DATETIME NOT NULL,
  PRIMAry KEY(id),
  INDEX(player_id)
) ENGINE=INNODB DEFAULT COLLATE=cp1257_bin CHARSET=cp1257;

ALTER TABLE player_jailtime ADD FOREIGN KEY(player_id) REFERENCES players(id) ON DELETE CASCADE;


CREATE TABLE IF NOT EXISTS player_crashes
(
  player_id INT(11) NOT NULL,
  timestamp DATETIME NOT NULL,
  pos_x FLOAT NOT NULL,
  pos_y FLOAT NOT NULL,
  pos_z FLOAT NOT NULL,
  interior INT NOT NULL,
  virtual_world INT NOT NULL,
  PRIMARY KEY(player_id)
);
ALTER TABLE player_crashes ADD FOREIGN KEY(player_id) REFERENCES players(id) ON DELETE CASCADE;


CREATE TABLE `ltrp-java`.logs_admin
(
  id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  admin_name VARCHAR(24) NOT NULL,
  user_id INT NULL,
  date DATETIME NOT NULL,
  action VARCHAR(255) NOT NULL
) ENGINE=INNODB DEFAULT CHARSET=cp1257 COLLATE=cp1257_bin;


CREATE TABLE IF NOT EXISTS items
(
  id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  name VARCHAR(100) NOT NULL,
  class_name VARCHAR(100) NOT NULL,
  location_class VARCHAR(16) NOT NULL DEFAULT 'player',
  location_id INT NOT NULL,
  type INT NOT NULL,
  stackable TINYINT NOT NULL DEFAULT '0',
  amount SMALLINT UNSIGNED NOT NULL DEFAULT '1',
  doses_left INT NULL,
  weapon_model TINYINT NULL,
  ammo SMALLINT NULL,
  model_id INT NULL,
  bone TINYINT UNSIGNED NULL,
  anim_lib VARCHAR(30) NULL,
  anim_name VARCHAR(60) NULL,
  dmg_increase FLOAT NULL,
  phonenumber INT NULL UNIQUE,
  durability INT NULL,
  max_durability INT NULL,
  items INT NULL,
  size INT NULL,
  special_action TINYINT NULL
) ENGINE=INNODB DEFAULT CHARSET=cp1257 COLLATE=cp1257_bin;


CREATE TABLE IF NOT EXISTS phone_sms (
  id INT AUTO_INCREMENT NOT NULL,
  sender_number INT NOT NULL,
  recipient_number INT NOT NULL,
  `date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `text` VARCHAR(128) NOT NULL,
  `read` BOOLEAN NOT NULL DEFAULT '0',
  PRIMARY KEY(id),
  INDEX(sender_number),
  INDEX(recipient_number)
) ENGINE=INNODB DEFAULT CHARSET=cp1257 COLLATE=cp1257_bin;

CREATE TABLE IF NOT EXISTS phone_contacts (
  id INT AUTO_INCREMENT NOT NULL,
  number int(11) NOT NULL,
  contact_number int(11) NOT NULL,
  name varchar(24) NOT NULL,
  entry_date int(11) NOT NULL,
  PRIMARY KEY (id),
  INDEX(number),
  INDEX(contact_number)
) ENGINE=InnoDB DEFAULT CHARSET=cp1257;

 -- The main parent big super important table

CREATE TABLE IF NOT EXISTS items
(
  id INT AUTO_INCREMENT NOT NULL,
  type INT NOT NULL,
  type_class VARCHAR(64) NOT NULL,
  location VARCHAR(64) NOT NULL,
  location_id INT NOT NULL,
  item_id INT NOT NULL,
  PRIMARY KEY(id)
)ENGINE=INNODB DEFAULT CHARSET=cp1257 COLLATE=cp1257_bin;

CREATE TABLE IF NOT EXISTS items_basic
(
  id INT AUTO_INCREMENT NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  stackable BOOLEAN NOT NULL DEFAULT '0',
  PRIMARY KEY(id)
) ENGINE=INNODB DEFAULT CHARSET=cp1257 COLLATE=cp1257_bin;

CREATE TABLE IF NOT EXISTS items_durable
(
  id INT AUTO_INCREMENT NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  stackable BOOLEAN NOT NULL DEFAULT '0',
  durability INT NOT NULL DEFAULT '0',
  max_durability INT NOT NULL DEFAULT '0',
  PRIMARY KEY(id)
) ENGINE=INNODB DEFAULT CHARSET=cp1257 COLLATE=cp1257_bin;


CREATE TABLE IF NOT EXISTS items_container
(
  id INT AUTO_INCREMENT NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  stackable BOOLEAN NOT NULL DEFAULT '0',
  items INT NOT NULL DEFAULT '0',
  size INT NOT NULL DEFAULT '0',
  PRIMARY KEY(id)
) ENGINE=INNODB DEFAULT CHARSET=cp1257 COLLATE=cp1257_bin;

CREATE TABLE IF NOT EXISTS items_clothing
(
  id INT AUTO_INCREMENT NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  stackable BOOLEAN NOT NULL DEFAULT '0',
  model SMALLINT NOT NULL DEFAULT  '0',
  bone TINYINT UNSIGNED NOT NULL DEFAULT  '0',
  worn BOOLEAN NOT NULL DEFAULT '0',
  PRIMARY KEY (id)
) ENGINE=INNODB DEFAULT CHARSET=cp1257 COLLATE=cp1257_bin;

CREATE TABLE IF NOT EXISTS items_melee_weapon
(
  id INT AUTO_INCREMENT NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  stackable BOOLEAN NOT NULL DEFAULT '0',
  model SMALLINT NOT NULL DEFAULT  '0',
  bone TINYINT UNSIGNED NOT NULL DEFAULT  '0',
  worn BOOLEAN NOT NULL DEFAULT '0',
  anim_lib VARCHAR(64) NOT NULL DEFAULT 'none',
  anim_name VARCHAR(64) NOT NULL DEFAULT 'none',
  dmg_increase FLOAT NOT NULL DEFAULT '0',
  PRIMARY KEY (id)
) ENGINE=INNODB DEFAULT CHARSET=cp1257 COLLATE=cp1257_bin;

CREATE TABLE IF NOT EXISTS items_weapon
(
  id INT AUTO_INCREMENT NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  stackable BOOLEAN NOT NULL DEFAULT '0',
  weapon_id TINYINT NOT NULL DEFAULT '0',
  ammo SMALLINT UNSIGNED NOT NULL DEFAULT '0',
  PRIMARY KEY (id)
) ENGINE=INNODB DEFAULT CHARSET=cp1257 COLLATE=cp1257_bin;

CREATE TABLE IF NOT EXISTS items_consumable
(
  id INT AUTO_INCREMENT NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  stackable BOOLEAN NOT NULL DEFAULT '0',
  doses INT NOT NULL DEFAULT '0',
  PRIMARY KEY (id)
) ENGINE=INNODB DEFAULT CHARSET=cp1257 COLLATE=cp1257_bin;

CREATE TABLE IF NOT EXISTS items_drink
(
  id INT AUTO_INCREMENT NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  stackable BOOLEAN NOT NULL DEFAULT '0',
  doses INT NOT NULL DEFAULT '0',
  special_action TINYINT UNSIGNED NOT NULL DEFAULT '0',
  PRIMARY KEY (id)
) ENGINE=INNODB DEFAULT CHARSET=cp1257 COLLATE=cp1257_bin;

CREATE TABLE IF NOT EXISTS items_phone
(
  id INT AUTO_INCREMENT NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  stackable BOOLEAN NOT NULL DEFAULT '0',
  number INT NOT NULL DEFAULT '86000000',
  PRIMARY KEY (id)
) ENGINE=INNODB DEFAULT CHARSET=cp1257 COLLATE=cp1257_bin;

CREATE TABLE IF NOT EXISTS items_radio
(
  id INT AUTO_INCREMENT NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  frequency FLOAT NOT NULL DEFAULT '0.0',
  PRIMARY KEY (id)
)ENGINE=INNODB DEFAULT CHARSET=cp1257 COLLATE=cp1257_bin;

CREATE TABLE house_weed
(
  id INT NOT NULL AUTO_INCREMENT,
  house_id INT NOT NULL,
  x REAL NOT NULL,
  y REAL NOT NULL,
  z REAL NOT NULL,
  plant_timestamp INT NOT NULL,
  planted_by INT NOT NULL,
  growth_timestamp INT DEFAULT 0 NOT NULL,
  growth_stage TINYINT UNSIGNED DEFAULT 0 NOT NULL,
  harvested_by INT NULL,
  yield TINYINT UNSIGNED NULL,
  PRIMARY KEY(id),
  INDEX(planted_by),
  INDEX(harvested_by)
) ENGINE=INNODB DEFAULT CHARSET=cp1257 COLLATE=cp1257_bin;


CREATE TABLE IF NOT EXISTS player_crimes
(
  id INT AUTO_INCREMENT NOT NULL,
  name VARCHAR(24) NOT NULL,
  crime VARCHAR(128) NOT NULL,
  reporter VARCHAR(24) NOT NULL,
  date DATETIME NOT NULL,
  PRIMARY KEY(id)
)ENGINE=INNODB DEFAULT CHARSET=cp1257 COLLATE=cp1257_bin;

CREATE TABLE IF NOT EXISTS player_licenses
(
  id INT AUTO_INCREMENT NOT NULL,
  player_id INT NOT NULL,
  type VARCHAR(24) NOT NULL,
  stage TINYINT UNSIGNED NOT NULL,
  date DATETIME NOT NULL,
  PRIMARY KEY (id)
) ENGINE=INNODB DEFAULT CHARSET=cp1257 COLLATE=cp1257_bin;

CREATE TABLE IF NOT EXISTS player_license_warnings
(
  id INT AUTO_INCREMENT NOT NULL,
  license_id INT NOT NULL,
  warning VARCHAR(512) NOT NULL,
  issued_by VARCHAR(24) NOT NULL,
  date DATETIME NOT NULL,
  PRIMARY KEY (id)
) ENGINE=INNODB DEFAULT CHARSET=cp1257 COLLATE=cp1257_bin;

CREATE TABLE IF NOT EXISTS dmv (
  id INT AUTO_INCREMENT NOT NULL,
  name VARCHAR(100) NOT NULL,
  type VARCHAR(24) NOT NULL,
  x FLOAT NOT NULL,
  y FLOAT NOT NULL,
  z FLOAT NOT NULL,
  interior INT NOT NULL,
  virtual_world INT NOT NULL,
  PRIMARY KEY (id)
)ENGINE=INNODB DEFAULT CHARSET=cp1257 COLLATE=cp1257_bin;

CREATE TABLE IF NOT EXISTS dmv_checkpoint
(
  id INT AUTO_INCREMENT NOT NULL,
  dmv_id INT NOT NULL,
  x FLOAT NOT NULL,
  y FLOAT NOT NULL,
  z FLOAT NOT NULL,
  radius FLOAT NOT NULL,
  PRIMARY KEY (id)
)ENGINE=INNODB DEFAULT CHARSET=cp1257 COLLATE=cp1257_bin;


CREATE TABLE IF NOT EXISTS dmv_vehicle
(
  id INT AUTO_INCREMENT NOT NULL,
  dmv_id INT NOT NULL,
  modelid SMALLINT UNSIGNED,
  x FLOAT NOT NULL,
  y FLOAT NOT NULL,
  z FLOAT NOT NULL,
  angle FLOAT NOT NULL,
  color1 TINYINT UNSIGNED NOT NULL ,
  color2 TINYINT UNSIGNED NOT NULL,
  PRIMARY KEY (id)
)ENGINE=INNODB DEFAULT CHARSET=cp1257 COLLATE=cp1257_bin;

CREATE TABLE IF NOT EXISTS dmv_question
(
  id INT AUTO_INCREMENT NOT NULL,
  dmv_id INT NOT NULL,
  question VARCHAR(1024) NOT NULL,
  PRIMARY KEY (id)
)ENGINE=INNODB DEFAULT CHARSET=cp1257 COLLATE=cp1257_bin;

CREATE TABLE IF NOT EXISTS dmv_question_answer
(
  id INT AUTO_INCREMENT NOT NULL,
  question_id INT NOT NULL,
  answer VARCHAR(512) NOT NULL,
  correct BOOLEAN NOT NULL,
  PRIMARY KEY (id)
)ENGINE=INNODB DEFAULT CHARSET=cp1257 COLLATE=cp1257_bin;


CREATE TABLE IF NOT EXISTS player_vehicle_permissions
(
  id INT AUTO_INCREMENT NOT NULL,
  player_id INT NOT NULL,
  vehicle_id INT NOT NULL,
  permission VARCHAR(64) NOT NULL,
  PRIMARY KEY  (id)
)ENGINE=INNODB DEFAULT CHARSET=cp1257 COLLATE=cp1257_bin;

CREATE TABLE IF NOT EXISTS player_vehicles
(
  id INT NOT NULL,
  owner_id INT NOT NULL,
  model_id SMALLINT UNSIGNED NOT NULL,
  x FLOAT NOT NULL,
  y FLOAT NOT NULL,
  z FLOAT NOT NULL,
  angle FLOAT NOT NULL,
  color1 TINYINT UNSIGNED NOT NULL,
  color2 TINYINT UNSIGNED NOT NULL,
  deaths INT NOT NULL,
  alarm VARCHAR(30) NOT NULL,
  lock_name VARCHAR(100) NOT NULL,
  lock_cracktime INT NOT NULL,
  lock_price INT NOT NULL,
  insurance TINYINT NOT NULL,
  license_plate VARCHAR(16) NOT NULL,
  doors INT NOT NULL,
  panels INT NOT NULL,
  lights INT NOT NULL,
  tires INT NOT NULL,
  PRIMARY KEY (id)
)ENGINE=INNODB DEFAULT CHARSET=cp1257 COLLATE=cp1257_bin;

CREATE TABLE IF NOT EXISTS player_vehicle_crimes
(
  id INT AUTO_INCREMENT NOT NULL,
  license_plate VARCHAR(24) NOT NULL,
  crime VARCHAR(128) NOT NULL,
  reporter VARCHAR(24) NOT NULL,
  date DATETIME NOT NULL,
  fine INT UNSIGNED NOT NULL,
  PRIMARY KEY(id)
)ENGINE=INNODB DEFAULT CHARSET=cp1257 COLLATE=cp1257_bin;