
CREATE TABLE players
(
  id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  username VARCHAR(24) DEFAULT 'Kas' NOT NULL,
  password VARCHAR(128) DEFAULT 'klaida' NOT NULL,
  secret_question VARCHAR(128) NOT NULL,
  secret_answer VARCHAR(128) NOT NULL,
  level INT DEFAULT 1 NOT NULL,
  admin_level INT DEFAULT 0 NOT NULL,
  connected_time INT DEFAULT 0 NOT NULL,
  box_style TINYINT UNSIGNED DEFAULT 4 NOT NULL,
  sex VARCHAR(11) DEFAULT 'Vyras' NOT NULL,
  age INT DEFAULT 0 NOT NULL,
  origin VARCHAR(24) DEFAULT 'Nenustatyta' NOT NULL,
  disease INT DEFAULT 0 NOT NULL,
  respect INT DEFAULT 0 NOT NULL,
  money INT DEFAULT 320 NOT NULL,
  bank INT DEFAULT 0 NOT NULL,
  deaths INT DEFAULT 0 NOT NULL,
  wanted_level INT DEFAULT 0 NOT NULL,
  job INT DEFAULT 0 NOT NULL,
  leader INT DEFAULT 0 NOT NULL,
  member INT DEFAULT 0 NOT NULL,
  pJobCar INT DEFAULT 0 NOT NULL,
  rank INT DEFAULT 0 NOT NULL,
  skin INT DEFAULT 212 NOT NULL,
  job_contract TINYINT DEFAULT 0 NOT NULL,
  phonenumber INT DEFAULT 0 NOT NULL,
  House INT DEFAULT 0 NOT NULL,
  CarLic INT DEFAULT 0 NOT NULL,
  FlyLic INT DEFAULT 0 NOT NULL,
  BoatLic INT DEFAULT 0 NOT NULL,
  MotoLic INT DEFAULT 0 NOT NULL,
  GunLic INT DEFAULT 0 NOT NULL,
  payday INT DEFAULT 0 NOT NULL,
  pay_day_had INT DEFAULT 0 NOT NULL,
  warnings INT DEFAULT 0 NOT NULL,
  virtual_world INT DEFAULT 0 NOT NULL,
  locked INT DEFAULT 0 NOT NULL,
  radio_channel INT DEFAULT 0 NOT NULL,
  ucpuser INT DEFAULT 0 NOT NULL,
  inventory VARCHAR(80) DEFAULT '0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/' NOT NULL,
  weapons VARCHAR(56) DEFAULT '0/0/0/0/0/0/0/0/' NOT NULL,
  pDubKey INT DEFAULT 0 NOT NULL,
  JobSkill INT DEFAULT 0 NOT NULL,
  JobLevel INT DEFAULT 0 NOT NULL,
  LeftTime INT DEFAULT 0 NOT NULL,
  DriverWarn INT DEFAULT 0 NOT NULL,
  Tester INT DEFAULT 0 NOT NULL,
  pFines INT DEFAULT 0 NOT NULL,
  pPFines INT DEFAULT 0 NOT NULL,
  pDutyT INT DEFAULT 0 NOT NULL,
  Donator INT DEFAULT 0 NOT NULL,
  Accepted VARCHAR(255) NOT NULL,
  WalkStyle INT NOT NULL,
  TalkStyle INT NOT NULL,
  TelNrKeite INT DEFAULT 0 NOT NULL,
  MasinosNrKeite INT DEFAULT 0 NOT NULL,
  DuziusKeite INT DEFAULT 0 NOT NULL,
  VardaKeite INT DEFAULT 0 NOT NULL,
  SenasVardas VARCHAR(255) DEFAULT 'Nera' NOT NULL,
  HeroineAddict SMALLINT DEFAULT 0 NOT NULL,
  AmfaAddict SMALLINT DEFAULT 0 NOT NULL,
  MetamfaAddict SMALLINT DEFAULT 0 NOT NULL,
  CocaineAddict SMALLINT DEFAULT 0 NOT NULL,
  playerIP VARCHAR(32) DEFAULT '127.0.0.1' NOT NULL,
  playerLastLogOn TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  spawn_type SMALLINT NOT NULL DEFAULT '0',
  spawn_ui INT NOT NULL DEFAULT '0',
  Card VARCHAR(256) DEFAULT 'Tuščia' NOT NULL,
  ForumName VARCHAR(256) DEFAULT 'Neivesta' NOT NULL,
  aDutyTime INT DEFAULT 0 NOT NULL,
  DonatorDate TIMESTAMP DEFAULT '0000-00-00 00:00:00' NOT NULL,
  HaveNameChange INT DEFAULT 0 NOT NULL,
  HavePhNrChange INT DEFAULT 0 NOT NULL,
  HaveVehPlatesChange INT DEFAULT 0 NOT NULL,
  HaveVehDestr INT DEFAULT 0 NOT NULL,
  ExtazyAddict SMALLINT DEFAULT 0 NOT NULL,
  PCPAddict SMALLINT DEFAULT 0 NOT NULL,
  CrackAddict SMALLINT DEFAULT 0 NOT NULL,
  OpiumAddict SMALLINT DEFAULT 0 NOT NULL,
  Points SMALLINT DEFAULT 0 NOT NULL,
  HealthLevel SMALLINT DEFAULT 0 NOT NULL,
  StrengthLevel SMALLINT DEFAULT 0 NOT NULL,
  ISP VARCHAR(128) DEFAULT '' NOT NULL,
  JobHours INT DEFAULT 0 NOT NULL,
  Hunger TINYINT UNSIGNED DEFAULT 0 NOT NULL,
  TotalPaycheck INT UNSIGNED DEFAULT 0 NOT NULL,
  radio_slot TINYINT UNSIGNED DEFAULT 1 NOT NULL
);


CREATE TABLE IF NOT EXISTS player_crashes
(
  player_id INT(11) NOT NULL,
  timestamp DATETIME NOT NULL,
  pos_x FLOAT NOT NULL,
  pos_y FLOAT NOT NULL,
  pos_z FLOAT NOT NULL,
  PRIMARY KEY(player_id)
);
ALTER TABLE player_crashes ADD FOREIGN KEY(player_id) REFERENCES players(id) ON DELETE CASCADE;


CREATE TABLE IF NOT EXISTS player_jailtime
(
  player_id INT NOT NULL,
  reamining_time INT NOT NULL,
  type VARCHAR(16) NOT NULL,
  jailer_id VARCHAR(24) NOT NUlL,
  PRIMAry KEY(player_id),
  INDeX(jailer_id)
) ENGINE=INNODB DEFAULT COLLATE=cp1257_bin CHARSET=cp1257;

ALTER TABLE player_jailtime ADD FOREIGN KEY(player_id) REFERENCES players(id) ON DELETE CASCADE;


CREATE TABLE IF NOT EXISTS player_crashes
(
  player_id INT(11) NOT NULL,
  timestamp DATETIME NOT NULL,
  pos_x FLOAT NOT NULL,
  pos_y FLOAT NOT NULL,
  pos_z FLOAT NOT NULL,
  interior INT NOT NULL,
  virtual_world INT NOT NULL,
  PRIMARY KEY(player_id)
);
ALTER TABLE player_crashes ADD FOREIGN KEY(player_id) REFERENCES players(id) ON DELETE CASCADE;


CREATE TABLE `ltrp-java`.logs_admin
(
  id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  admin_name VARCHAR(24) NOT NULL,
  user_id INT NULL,
  date DATETIME NOT NULL,
  action VARCHAR(255) NOT NULL
) ENGINE=INNODB DEFAULT CHARSET=cp1257 COLLATE=cp1257_bin;