CREATE TABLE IF NOT EXISTS vehicle_shop_vehicles (
  id INT AUTO_INCREMENT NOT NULL ,
  shop_id INT NOT NULL ,
  model_id SMALLINT NOT NULL ,
  price INT UNSIGNED NOT NULL ,
  PRIMARY KEY (id),
  FOREIGN KEY (shop_id) REFERENCES vehicle_shops(id) ON DELETE CASCADE
)ENGINE=INNODB DEFAULT CHARSET=cp1257 COLLATE=cp1257_bin;