
-- player_vehicles nëra "cCrimes". Jiems planuoju atskirus table.


CREATE TABLE IF NOT EXISTS player_vehicles (
	id AUTO_INCREMENT NOT NULL,
	owner INT NOT NULL,
	model SMALLINT NOT NULL,
	x FLOAT NOT NULL,
	y FLOAT NOT NULL,
	z FLOAT NOT NULL,
	angle FLOAT NOT NULL,
	color1 TINYINT UNSIGNED NOT NULL,
	color2 TINYINT UNSIGNED NOT NULL,
	locked BOOLEAN NOT NULL DEFAULT '0',
	lock_level TINYINT UNSIGNED NOT NULL,
	fuel SMALLINT NOT NULL,
	license_plate VARCHAR(16) NOT NULL DEFAULT '-',
	insurance TINYINT UNSIGNED NOT NULL DEFAULT '0',
	times_crashed TINYINT UNSIGNED NOT NULL DEFAULT '0',
	alarm_level TINYINT UNSIGNED NOT NULL DEFAULT '0',
	vehicle_id SMALLINT NOT NULL DEFAULT '0',
	panels INT NOT NULL DEFAULT '0',,
	doors INT NOT NULL DEFAULT '0',
	lights INT NOT NULL DEFAULT '0',
	tires INT NOT NULL DEFAULT '0',
	health FLOAT NOT NULL DEFAULT '1000.0',
	mileage FLOAT NOT NULL DEFAULT '0',
	virtual_world SMALLINT NOT NULL DEFAULT '0',
	faction TINYINT NULL DEFAULT NULL,
	PRIMARY KEY(id),
	INDEX(owner),
	INDEX(model),
	INDEX(faction)
) ENGINE=INNODB DEFAULT CHARSET=cp1257 COLLATE=cp1257_bin;

ALTER TABLE player_vehicles ADD FOREIGN KEY(owner) REFERENCES players(id) ON DELETE CASCADE;
ALTER TABLE player_vehicles ADD FOREIGN KEY(faction) REFERENCES factions(id) ON DELETE SET NULL;

CREATE TABLE IF NOT EXISTS vehicle_components 
(
	vehicle_id INT NOT NULL,
	component_id SMALLINT UNSIGNED NOT NULL,
	PRIMARY KEY(vehicle_id, component_id)
) ENGINE=INNODB DEFAULT CHARSET=cp1257 COLLATE=cp1257_bin;

ALTER TABLE vehicle_components ADD FOREIGN KEY(vehicle_id) REFERENCES player_vehicles(id) ON DELETE CASCADE;

CREATE TABLE IF NOT EXISTS vehicle_items 
(
	id INT AUTO_INCREMENT NOT NULL,
	vehicle_id INT NOT NULL,
	item_id INT NOT NULL,
	amount INT NOT NULL,
	content_amount INT NOT NULL DEFAULT '0',
	durability INT NOT NULL DEFAULT '0',
	PRIMARY KEY(id),
	INDEX(vehicle_id)
) ENGINE=INNODB DEFAULT CHARSET=cp1257 COLLATE=cp1257_bin;

ALTER TABLE vehicle_items ADD FOREIGN KEY(vehicle_id) REFERENCES player_vehicles(id) ON DELETE CASCADE;



CREATE TABLE IF NOT EXISTS vehicle_tickets 
(
	id INT AUTO_INCREMENT NOT NULL,
	vehicle_id INT NOT NULL,
	officer_name VARCHAR(24) NOT NULL,
	amount INT NOT NULL,
	`date` DATE NOT NULL DEFAULT CURRENT_TIMESTAMP,
	paid BOOLEAN NOT NULL DEFAULT '0',
	PRIMARY KEY(id),
	INDEX(vehicle_id)
) ENGINE=INNODB DEFAULT CHARSET=cp1257 COLLATE=cp1257_bin;

ALTER TABLE vehicle_tickets ADD FOREIGN KEY(vehicle_id) REFERENCES player_vehicles(id) ON DELETE CASCADE;